### ISSUE TITLE
versioned release with jar

### ISSUE THREAD

**Issue by jefferis** [saalfeldlab/transform-helpers#1]
Would it be worth making a release and uploading a jar? This is working for me right now.

**Comment by bogovicj** [comment]
There are now releases of this repo's dependencies.   b998c6c
@axtimwalde , agree that it makes sense to make a release?

**Comment by axtimwalde** [comment]
Greg was working with the fat jar, and I do not think that releasing the fat jar is a good idea.  Greg, can you try toi build the fat jar with `mvn -Pfat clean package`?

**Comment by jefferis** [comment]
Just to confirm that I was able to build the fat jar ok with `mvn -Pfat clean`. 

On MacOS X,  I have JDK 11 installed via https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html and maven installed via [homebrew](https://brew.sh) with:

```
brew install maven
```

**Comment by bogovicj** [comment]
https://github.com/saalfeldlab/transform-helpers/releases/tag/0.0.3
