### ISSUE TITLE
update n5-imglib2 version after next release

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/transform-helpers#3]
The newest n5-imglib2 changes the default out-of-bounds strategy.
https://github.com/saalfeldlab/n5-imglib2/commit/c72b0ea72d895ab78d9959aeaa0f48143a56ca0d

This gives more reasonable results when transforming points at / past the boundary and the displacement field takes large values at the boundary of the volumes - this is the case for the hemibrain dataset.

@schlegelp

**Comment by jefferis** [comment]
@bogovicj are you ready to update?

**Comment by bogovicj** [comment]
release ready: 
https://github.com/saalfeldlab/n5-imglib2/releases/tag/3.4.0
