### ISSUE TITLE
Handling of default level

### ISSUE THREAD

**Issue by jefferis** [saalfeldlab/transform-helpers#4]
@bogovicj has prepared multi-resolution transform files at https://www.janelia.org/open-science/jrc-2018-brain-templates. To use them one must specify the preferred level.

* Would it be possible to have the transform helper choose a default level (probably the finest resolution) when no explicit level is specified?

The reason is that since some h5 format registrations are multiresolution and others are not, one needs an external hdf5 reader tool to peek inside the transformation file in order to define an appropriate registration level.

**Comment by jefferis** [comment]
More specifically, these means that the https://github.com/natverse/nat.h5reg R package *must* have an install of the HDF5 C library in addition to the Java HDF5 library that comes with this tool.

**Comment by bogovicj** [comment]
>Would it be possible to have the transform helper choose a default level (probably the finest resolution) when no explicit level is specified?

Good point.  Latest commit implements this.  Okay to close this issue?

As well, shall I cut a new release?
