### ISSUE TITLE
log4shell mitigation

### ISSUE THREAD

**Issue by clbarnes** [saalfeldlab/transform-helpers#6]
According to https://github.com/rubo77/log4j_checker_beta , there are possibly vulnerable log4j files in the jar built by this project. We're getting it 3rd-hand (packaged with nat.h5reg to support a CATMAID installation); could you confirm whether we should be doing anything about it or if we can open our server up again?

**Comment by bogovicj** [comment]
Thanks for the ping @clbarnes ,

This repo transitively depended on log4j through [`jitk-tps`](https://github.com/saalfeldlab/jitk-tps).  Last week I removed log4j as a dep for that artifact, so I think updating to that new version should deal with that warning.  

Edit:
There's now a [0.0.2 release](https://github.com/saalfeldlab/transform-helpers/releases/tag/0.0.2) of this repo.

I hope that will address this issue, let me know if there's anything else I can help with.

**Comment by clbarnes** [comment]
Thanks John! It looks like that should resolve things for us (we had this package via nat.h5reg, which seems to just pull the latest commit).
